# Generated by Django 2.2.12 on 2021-02-19 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WXCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WXGProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='商品名')),
                ('cover_img', models.CharField(max_length=3000, null=True, verbose_name='商品主图')),
                ('attach_img_1', models.CharField(blank=True, max_length=3000, null=True, verbose_name='商品幅图1')),
                ('attach_img_2', models.CharField(blank=True, max_length=3000, null=True, verbose_name='商品幅图2')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('spec', models.TextField(blank=True, default='None', null=True, verbose_name='描述')),
                ('total_sales', models.IntegerField(blank=True, default=0, null=True, verbose_name='销售量')),
                ('body', models.CharField(blank=True, max_length=3000, null=True, verbose_name='详情页')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.WXCategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品表',
                'verbose_name_plural': '商品表',
                'ordering': ['id'],
            },
        ),
    ]
