# Generated by Django 2.2.12 on 2021-02-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_mywxuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mywxuser',
            options={'ordering': ['id'], 'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
