# Generated by Django 2.2.12 on 2021-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_auto_20210222_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='wxddaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auser', models.CharField(max_length=5, verbose_name='用户id')),
                ('aname', models.CharField(blank=True, max_length=60, null=True, verbose_name='收货人')),
                ('aphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('city', models.CharField(blank=True, max_length=500, null=True, verbose_name='省市')),
                ('aaddress', models.CharField(blank=True, max_length=500, null=True, verbose_name='详细地址')),
                ('adefaultaddress', models.CharField(default='2', max_length=5, verbose_name='是否默认地址')),
            ],
            options={
                'verbose_name': '地址表',
                'verbose_name_plural': '地址表',
                'ordering': ['id'],
            },
        ),
    ]
