# Generated by Django 2.2.12 on 2021-03-03 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_wxddaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='wxdindan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxuserid', models.CharField(blank=True, max_length=1000, null=True, verbose_name='用户id')),
                ('wxopenid', models.CharField(blank=True, max_length=1000, null=True, verbose_name='用户openid')),
                ('wxusertext', models.CharField(blank=True, max_length=1000, null=True, verbose_name='用户备注')),
                ('fapiao', models.CharField(blank=True, max_length=1000, null=True, verbose_name='发票抬头')),
                ('fapiaohaoma', models.CharField(blank=True, max_length=1000, null=True, verbose_name='发票税号')),
                ('paymode', models.CharField(blank=True, default=1, max_length=1000, null=True, verbose_name='支付方式')),
                ('addressid', models.CharField(blank=True, max_length=1000, null=True, verbose_name='地址id')),
                ('productid', models.CharField(blank=True, max_length=1000, null=True, verbose_name='商品id')),
                ('count', models.CharField(blank=True, max_length=1000, null=True, verbose_name='购买数量')),
                ('payzt', models.CharField(blank=True, max_length=1000, null=True, verbose_name='支付状态')),
                ('dindanbianhao', models.CharField(blank=True, max_length=200, null=True, verbose_name='订单编号')),
                ('totalprice', models.CharField(blank=True, max_length=200, null=True, verbose_name='总货款')),
                ('add_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='提交订单时间')),
                ('kuaidigonshi', models.CharField(blank=True, max_length=200, null=True, verbose_name='快递公司')),
                ('kuaididanhao', models.CharField(blank=True, max_length=200, null=True, verbose_name='快递单号')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'ordering': ['id'],
            },
        ),
    ]
