# Generated by Django 2.2.12 on 2021-03-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_wxdindan'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxdindan',
            name='is_receipt',
            field=models.CharField(default='2', max_length=5, verbose_name='是否确认收货'),
        ),
        migrations.AddField(
            model_name='wxdindan',
            name='is_ship',
            field=models.CharField(default='2', max_length=5, verbose_name='是否已经发货'),
        ),
    ]
