# Generated by Django 2.2.12 on 2021-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_auto_20210303_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='wxcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxuserid', models.CharField(blank=True, max_length=1000, null=True, verbose_name='用户id')),
                ('wxgoodsid', models.CharField(blank=True, max_length=1000, null=True, verbose_name='商品id')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='评价内容')),
                ('counts', models.IntegerField(blank=True, max_length=1, null=True, verbose_name='评分')),
            ],
            options={
                'verbose_name': '评价表',
                'verbose_name_plural': '评价表',
                'ordering': ['id'],
            },
        ),
    ]
