# Generated by Django 2.2.12 on 2021-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0008_auto_20210310_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxdindan',
            name='is_comment',
            field=models.CharField(default='2', max_length=5, verbose_name='是否评价'),
        ),
    ]
